/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 *
 * HDF is dual licensed: you can use it either under the terms of
 * the GPL, or the BSD license, at your option.
 * See the LICENSE file in the root of this repository for complete details.
 */

#ifndef HDF_AUDIO_DRIEVR_TEST_H
#define HDF_AUDIO_DRIEVR_TEST_H

#include "hdf_main_test.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif /* __cplusplus */

typedef enum {
    AUDIO_DRIVER_TESTDAIHWPARAMS,
    AUDIO_DRIVER_TESTDAI_INVALID_RATE_PARAM,
    AUDIO_DRIVER_TESTDAI_INVALID_RENDER_BITWIDTH_RARAM,
    AUDIO_DRIVER_TESTDAI_INVALID_CAPTURE_BITWIDTH_RARAM,
    AUDIO_DRIVER_TESTDAI_INVALID_STREAMTYPE_RARAM,
    AUDIO_DRIVER_TESTDAI_TRIGGER,

    AUDIO_DRIVER_TESTAUDIOPLATFORMDEVICEINIT,
    AUDIO_DRIVER_TESTPLATFORMHWPARAMS,
    AUDIO_DRIVER_TESTPLATFORM_INVALID_CHANNELS_NUMBER_PARAM,
    AUDIO_DRIVER_TESTPLATFORM_INVALID_STREAM_TYPE_PARAM,
    AUDIO_DRIVER_TESTPLATFORM_INVALID_RENDER_PERIOD_COUNT_PARAM,
    AUDIO_DRIVER_TESTPLATFORM_INVALID_RENDER_PERIODSIZE_PARAM,
    AUDIO_DRIVER_TESTPLATFORM_INVALID_CAPTURE_PERIOD_COUNT_PARAM,
    AUDIO_DRIVER_TESTPLATFORM_INVALID_CAPTURE_PERIODSIZE_PARAM,
    AUDIO_DRIVER_TESTPLATFORM_INVALID_CAPTURE_SILENCETHRESHOLD_PARAM,
    AUDIO_DRIVER_TESTPLATFORMRENDERPREPARE,
    AUDIO_DRIVER_TESTPLATFORMCAPTUREPREPARE,
    AUDIO_DRIVER_TESTPLATFORMWRITE,
    AUDIO_DRIVER_TESTPLATFORMREAD,
    AUDIO_DRIVER_TESTPLATFORMRENDERSTART,
    AUDIO_DRIVER_TESTPLATFORMCAPTURESTART,
    AUDIO_DRIVER_TESTPLATFORMREANERSTOP,
    AUDIO_DRIVER_TESTPLATFORMCAPTUERSTOP,
    AUDIO_DRIVER_TESTPLAFORMRENDERPAUSE,
    AUDIO_DRIVER_TESTPLATFORMRENDERRESUME,
    AUDIO_DRIVER_TESTPLATFORMCAPUTERPAUSE,
    AUDIO_DRIVER_TESTPLATFORMCAPTURERESUME,

    AUDIO_DRIVER_TESTCODECHALSYSINIT,
    AUDIO_DRIVER_TESTACODECDEVICEININ,
    AUDIO_DRIVER_TESTACODECHALREADREG,
    AUDIO_DRIVER_TESTACODECHALWRITEREG,
    AUDIO_DRIVER_TESTACODECSETI2S1FS,
    AUDIO_DRIVER_TESTACODECSETI2S1FSINVALIDRATE,
    AUDIO_DRIVER_TESTACODECSETI2S1DATAWIDTH,
    AUDIO_DRIVER_TESTACODECSETI2S1DATAWIDTHINVALIDBITWIDTH,

    AUDIO_DRIVER_TESTCODECDEVICEINIT,
    AUDIO_DRIVER_TESTCODECDEVICEINITFAIL,
    AUDIO_DRIVER_TESTCODECDAIDEVICEINIT,
    AUDIO_DRIVER_TESTCODECDAIDEVICEINITFAIL,
    AUDIO_DRIVER_TESTCODECDAIHWPARAMS,
    AUDIO_DRIVER_TESTCODECDAI_INVALID_BITWIDTH_PARAM,
    AUDIO_DRIVER_TESTCODECDAIINVALID_RATE_PARAM,
    AUDIO_DRIVER_TESTCODECDAISTARTUP,

    AUDIO_DRIVER_TESTAIAOHALSYSINIT,
    AUDIO_DRIVER_TESTAIAOCLOCKRESET,
    AUDIO_DRIVER_TESTAIAOHALREADREG,
    AUDIO_DRIVER_TESTAOPHALSETBUFFRPTR,
    AUDIO_DRIVER_TESTAOPHALSETBUFFRPTRINVALIDCHANID,
    AUDIO_DRIVER_TESTAOPHALSETBUFFWPTR,
    AUDIO_DRIVER_TESTAOPHALSETBUFFWPTRINVALIDCHNID,
    AUDIO_DRIVER_TESTAOPHALSETBUFFERADDR,
    AUDIO_DRIVER_TESTAOPHALSETBUFFERADDRINVALIDCHNID,
    AUDIO_DRIVER_TESTAIPHALSETBUFFERADDR,
    AUDIO_DRIVER_TESTAIPHALSETBUFFERADDRINVALIDCHNID,
    AUDIO_DRIVER_TESTAIPHALSETBUFFERSIZE,
    AUDIO_DRIVER_TESTAIPHALSETBUFFERSIZEINVALIDCHNID,
    AUDIO_DRIVER_TESTAIPHALSETTRANSSIZE,
    AUDIO_DRIVER_TESTAIPHALSETTRANSSIZEINVALIDCHNID,
    AUDIO_DRIVER_TESTAIPHALSETRXSTART,
    AUDIO_DRIVER_TESTAIPHALSETRXSTARTINVALIDCHNID,
    AUDIO_DRIVER_TESTAIPHALSETBUFFWPTR,
    AUDIO_DRIVER_TESTAIPHALSETBUFFWPTRINVALIDCHNID,
    AUDIO_DRIVER_TESTAIPHALSETBUFFRPTR,
    AUDIO_DRIVER_TESTAIPHALSETBUFFRPTRINVALIDCHNID,
    AUDIO_DRIVER_TESTAOPHALSETBUFFERSIZE,
    AUDIO_DRIVER_TESTAOPHALSETBUFFERSIZEINVALIDCHNID,
    AUDIO_DRIVER_TESTAOPHALSETTRANSSIZE,
    AUDIO_DRIVER_TESTAOPHALSETTRANSSIZEINVALIDCHNID,
    AUDIO_DRIVER_TESTAOPHALSETTXSTART,
    AUDIO_DRIVER_TESTAOPHALSETTXSTARTINVALIDCHNID,
    AUDIO_DRIVER_TESTSHOWALLAIAOREGISTER,
    AUDIO_DRIVER_TESTAOPHALDEVENABLE,
    AUDIO_DRIVER_TESTAIPBUFFRPTRREG,
    AUDIO_DRIVER_TESTAIPBUFFWPTRREG,
    AUDIO_DRIVER_TESTAOPBUFFRPTRREG,
    AUDIO_DRIVER_TESTAOPBUFFWPTRREG,
    AUDIO_DRIVER_TESTAOPSETSYSCTLREG,
    AUDIO_DRIVER_TESTAOPSETSYSCTLREGINVALIDRATE,
    AUDIO_DRIVER_TESTAOPSETATTR,
    AUDIO_DRIVER_TESTAOPSETATTRINVALIDCHANNELCNT,
    AUDIO_DRIVER_TESTAOPSETATTRINVALIDBITWIDTH,
    AUDIO_DRIVER_TESTAIPSETSYSCTLREG,
    AUDIO_DRIVER_TESTAIPSETSYSCTLREGINVALIDRATE,
    AUDIO_DRIVER_TESTAIPSETATTR,
    AUDIO_DRIVER_TESTAIPSETATTRINVALIDCHANNELCNT,
    AUDIO_DRIVER_TESTAIPSETATTRINVALIDBITWIDTH,
    AUDIO_DRIVER_TESTAIAODEVICEINIT,
    AUDIO_DRIVER_TESTI2SCRGCFGINIT,
} HdfHi3516DV300DirverTestCaseCmd;

int32_t HdfAudioDriverEntry(HdfTestMsg *msg);

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */

#endif /* HDF_DRIEVR_TEST_H */
