/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 *
 * HDF is dual licensed: you can use it either under the terms of
 * the GPL, or the BSD license, at your option.
 * See the LICENSE file in the root of this repository for complete details.
 */

#ifndef HDF_AUDIO_DRIEVR_TEST_H
#define HDF_AUDIO_DRIEVR_TEST_H

#include "hdf_main_test.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif /* __cplusplus */


typedef enum {
    AUDIO_DRIVER_TESTDAIHWPARAMS,

    AUDIO_DRIVER_TESTAUDIOPLATFORMDEVICEINIT,
    AUDIO_DRIVER_TESTPLATFORMHWPARAMS,
    AUDIO_DRIVER_TESTPLATFORMRENDERPREPARE,
    AUDIO_DRIVER_TESTPLATFORMCAPTUREPREPARE,
    AUDIO_DRIVER_TESTPLATFORMWRITE,
    AUDIO_DRIVER_TESTPLATFORMREAD,
    AUDIO_DRIVER_TESTPLATFORMRENDERSTART,
    AUDIO_DRIVER_TESTPLATFORMCAPTURESTART,
    AUDIO_DRIVER_TESTPLATFORMREANERSTOP,
    AUDIO_DRIVER_TESTPLATFORMCAPTUERSTOP,
    AUDIO_DRIVER_TESTPLAFORMRENDERPAUSE,
    AUDIO_DRIVER_TESTPLATFORMRENDERRESUME,
    AUDIO_DRIVER_TESTPLATFORMCAPUTERPAUSE,
    AUDIO_DRIVER_TESTPLATFORMCAPTURERESUME,

    AUDIO_DRIVER_TESTCODECHALSYSINIT,
    AUDIO_DRIVER_TESTACODECDEVICEININ,
    AUDIO_DRIVER_TESTACODECHALREADREG,
    AUDIO_DRIVER_TESTACODECHALWRITEREG,
    AUDIO_DRIVER_TESTACODECSETI2S1FS,
    AUDIO_DRIVER_TESTACODECSETI2S1DATAWIDTH,

    AUDIO_DRIVER_TESTCODECDEVICEINIT,
    AUDIO_DRIVER_TESTCODECDAIDEVICEINIT,
    AUDIO_DRIVER_TESTCODECDAIHWPARAMS,
    AUDIO_DRIVER_TESTCODECDAISTARTUP,

    AUDIO_DRIVER_TESTAIAOHALSYSINIT,
    AUDIO_DRIVER_TESTAIAOCLOCKRESET,
    AUDIO_DRIVER_TESTAIAOHALREADREG,
    AUDIO_DRIVER_TESTAOPHALSETBUFFRPTR,
    AUDIO_DRIVER_TESTAOPHALSETBUFFWPTR,
    AUDIO_DRIVER_TESTAOPHALSETBUFFERADDR,
    AUDIO_DRIVER_TESTAIPHALSETBUFFERADDR,
    AUDIO_DRIVER_TESTAIPHALSETBUFFERSIZE,
    AUDIO_DRIVER_TESTAIPHALSETTRANSSIZE,
    AUDIO_DRIVER_TESTAIPHALSETRXSTART,
    AUDIO_DRIVER_TESTAIPHALSETBUFFWPTR,
    AUDIO_DRIVER_TESTAIPHALSETBUFFRPTR,
    AUDIO_DRIVER_TESTAOPHALSETBUFFERSIZE,
    AUDIO_DRIVER_TESTAOPHALSETTRANSSIZE,
    AUDIO_DRIVER_TESTAOPHALSETTXSTART,
    AUDIO_DRIVER_TESTAOPHALDEVENABLE,
    AUDIO_DRIVER_TESTAIPBUFFRPTRREG,
    AUDIO_DRIVER_TESTAIPBUFFWPTRREG,
    AUDIO_DRIVER_TESTAOPBUFFRPTRREG,
    AUDIO_DRIVER_TESTAOPBUFFWPTRREG,
    AUDIO_DRIVER_TESTAOPSETSYSCTLREG,
    AUDIO_DRIVER_TESTAOPSETATTR,
    AUDIO_DRIVER_TESTAIPSETSYSCTLREG,
    AUDIO_DRIVER_TESTAIPSETATTR,
    AUDIO_DRIVER_TESTAIAODEVICEINIT,
    AUDIO_DRIVER_TESTI2SCRGCFGINIT,
} HdfHi3516DV300DirverTestCaseCmd;

int32_t HdfAudioDriverEntry(HdfTestMsg *msg);

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */

#endif /* HDF_DRIEVR_TEST_H */
