/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 *
 * HDF is dual licensed: you can use it either under the terms of
 * the GPL, or the BSD license, at your option.
 * See the LICENSE file in the root of this repository for complete details.
 */

#ifndef HI3516_AUDIO_DRIVER_TEST_H
#define HI3516_AUDIO_DRIVER_TEST_H

#include "hdf_types.h"

const int32_t G_TEST_HI3516_AUDIO_DRIVER_TYPE    = 702;

typedef enum {
    TESTDAIHWPARAMS,
    TESTDAIINVALIDRATEPARAM,            // invalid SampleRate
    TESTDAIINVALIDRENDERBITWIDTHPARAM,  // invalid bitwidth RENDER
    TESTDAIINVALIDCAPTUERBITWIDTHPARAM, // invalid bitwitdh CAPTURE
    TESTDAIINVALIDSTREAMTYPEPARAM,      // invalid stream type
    TESTDAITRIGGER,

    TESTAUDIOPLATFORMDEVICEINIT,
    TESTPLATFORMHWPARAMS,
    TESTPLATFORMINVALIDCHANSPARAM,
    TESTPLATFORMINVALIDSTREAMTYPEPARAM,
    TESTPLATFORMINVALIDRENDERPERIODCOUNTPARAM,
    TESTPLATFORMINVALIDRENDERPERIODSIZE,
    TESTPLATFORMINVALIDCAPTUREPERIODCOUNTPARAM,
    TESTPLATFORMINVALIDCAPTUREPERIODSIZE,
    TESTPLATFORMINVALIDCAPTURESILENCETHRESHOLDPARAM,
    TESTPLATFORMRENDERPREPARE,
    TESTPLATFORMCAPTUREPREPARE,
    TESTPLATFORMWRITE,
    TESTPLATFORMREAD,
    TESTPLATFORMRENDERSTART,
    TESTPLATFORMCAPTURESTART,
    TESTPLATFORMREANERSTOP,
    TESTPLATFORMCAPTUERSTOP,
    TESTPLATFORMCAPUTERPAUSE,
    TESTPLATFORMRENDERPAUSE,
    TESTPLATFORMRENDERRESUME,
    TESTPLATFORMCAPTURERESUME,

    TESTCODECHALSYSINIT,
    TESTACODECDEVICEININ,
    TESTACODECHALREADREG,
    TESTACODECHALWRITEREG,
    TESTACODECSETI2S1FS,
    TESTACODECSETI2S1FSINVALIDRATE,
    TESTACODECSETI2S1DATAWIDTH,
    TESTACODECSETI2S1DATAWIDTHINVALIDBITWIDTH,

    TESTCODECDEVICEINIT,
    TESTCODECDEVICEINITFAIL,
    TESTCODECDAIDEVICEINIT,
    TESTCODECDAIDEVICEINITFAIL,
    TESTCODECDAIHWPARAMS,
    TESTCODECDAIINVALIDBITWIDTHPARAM,
    TESTCODECDAIINVALIDRATEPARAM,
    TESTCODECDAISTARTUP,

    TESTAIAOHALSYSINIT,
    TESTAIAOCLOCKRESET,
    TESTAIAOHALREADREG,
    TESTAOPHALSETBUFFRPTR,
    TESTAOPHALSETBUFFRPTRINVALIDCHANID,
    TESTAOPHALSETBUFFWPTR,
    TESTAOPHALSETBUFFWPTRINVALIDCHNID,
    TESTAOPHALSETBUFFERADDR,
    TESTAOPHALSETBUFFERADDRINVALIDCHNID,
    TESTAIPHALSETBUFFERADDR,
    TESTAIPHALSETBUFFERADDRINVALIDCHNID,
    TESTAIPHALSETBUFFERSIZE,
    TESTAIPHALSETBUFFERSIZEINVALIDCHNID,
    TESTAIPHALSETTRANSSIZE,
    TESTAIPHALSETTRANSSIZEINVALIDCHNID,
    TESTAIPHALSETRXSTART,
    TESTAIPHALSETRXSTARTINVALIDCHNID,
    TESTAIPHALSETBUFFWPTR,
    TESTAIPHALSETBUFFWPTRINVALIDCHNID,
    TESTAIPHALSETBUFFRPTR,
    TESTAIPHALSETBUFFRPTRINVALIDCHNID,
    TESTAOPHALSETBUFFERSIZE,
    TESTAOPHALSETBUFFERSIZEINVALIDCHNID,
    TESTAOPHALSETTRANSSIZE,
    TESTAOPHALSETTRANSSIZEINVALIDCHNID,
    TESTAOPHALSETTXSTART,
    TESTAOPHALSETTXSTARTINVALIDCHNID,
    TESTSHOWALLAIAOREGISTER,
    TESTAOPHALDEVENABLE,
    TESTAIPBUFFRPTRREG,
    TESTAIPBUFFWPTRREG,
    TESTAOPBUFFRPTRREG,
    TESTAOPBUFFWPTRREG,
    TESTAOPSETSYSCTLREG,
    TESTAOPSETSYSCTLREGINVALIDRATE,
    TESTAOPSETATTR,
    TESTAOPSETATTRINVALIDCHANNELCNT,
    TESTAOPSETATTRINVALIDBITWIDTH,
    TESTAIPSETSYSCTLREG,
    TESTAIPSETSYSCTLREGINVALIDRATE,
    TESTAIPSETATTR,
    TESTAIPSETATTRINVALIDCHANNELCNT,
    TESTAIPSETATTRINVALIDBITWIDTH,
    TESTAIAODEVICEINIT,
    TESTI2SCRGCFGINIT,
}HdfHi3516AudioDriverTestCmd;


#endif /* HI3516_AUDIO_DRIVER_TEST_H */
