/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 *
 * HDF is dual licensed: you can use it either under the terms of
 * the GPL, or the BSD license, at your option.
 * See the LICENSE file in the root of this repository for complete details.
 */

#ifndef HI3516_AUDIO_DRIVER_TEST_H
#define HI3516_AUDIO_DRIVER_TEST_H

#include "hdf_types.h"

const int32_t G_TEST_HI3516_AUDIO_DRIVER_TYPE    = 702;

using HdfHi3516AudioDriverTestCmd = enum {
    TESTDAIHWPARAMS,

    TESTAUDIOPLATFORMDEVICEINIT,
    TESTPLATFORMHWPARAMS,
    TESTPLATFORMRENDERPREPARE,
    TESTPLATFORMCAPTUREPREPARE,
    TESTPLATFORMWRITE,
    TESTPLATFORMREAD,
    TESTPLATFORMRENDERSTART,
    TESTPLATFORMCAPTURESTART,
    TESTPLATFORMREANERSTOP,
    TESTPLATFORMCAPTUERSTOP,
    TESTPLATFORMCAPUTERPAUSE,
    TESTPLATFORMRENDERPAUSE,
    TESTPLATFORMRENDERRESUME,
    TESTPLATFORMCAPTURERESUME,

    TESTCODECHALSYSINIT,
    TESTACODECDEVICEININ,
    TESTACODECHALREADREG,
    TESTACODECHALWRITEREG,
    TESTACODECSETI2S1FS,
    TESTACODECSETI2S1DATAWIDTH,

    TESTCODECDEVICEINIT,
    TESTCODECDAIDEVICEINIT,
    TESTCODECDAIHWPARAMS,
    TESTCODECDAISTARTUP,

    TESTAIAOHALSYSINIT,
    TESTAIAOCLOCKRESET,
    TESTAIAOHALREADREG,
    TESTAOPHALSETBUFFRPTR,
    TESTAOPHALSETBUFFWPTR,
    TESTAOPHALSETBUFFERADDR,
    TESTAIPHALSETBUFFERADDR,
    TESTAIPHALSETBUFFERSIZE,
    TESTAIPHALSETTRANSSIZE,
    TESTAIPHALSETRXSTART,
    TESTAIPHALSETBUFFWPTR,
    TESTAIPHALSETBUFFRPTR,
    TESTAOPHALSETBUFFERSIZE,
    TESTAOPHALSETTRANSSIZE,
    TESTAOPHALSETTXSTART,
    TESTAOPHALDEVENABLE,
    TESTAIPBUFFRPTRREG,
    TESTAIPBUFFWPTRREG,
    TESTAOPBUFFRPTRREG,
    TESTAOPBUFFWPTRREG,
    TESTAOPSETSYSCTLREG,
    TESTAOPSETATTR,
    TESTAIPSETSYSCTLREG,
    TESTAIPSETATTR,
    TESTAIAODEVICEINIT,
    TESTI2SCRGCFGINIT,
};

#endif /* HI3516_AUDIO_DRIVER_TEST_H */
